apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmicroservice
  labels:
    app: dbmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmicroservice
  template:
    metadata:
      labels:
        app: dbmicroservice
    spec:
      containers:
      - name: dbmicroservice-container
        image: federicoand98/db-microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.3"
